import React, { useState } from 'react';
import { AutomaticAnalysisItem, FailureEventHistoryItem } from '../types';
import {
  Sparkles,
  CheckCircle2,
  AlertTriangle,
  AlertOctagon,
  Clock,
  Radio,
  ArrowRight,
  ShieldCheck,
  ShieldAlert,
  Search,
  MessageSquare,
  Activity,
  Flame,
  Atom,
  Layers,
  HelpCircle,
  History,
  RotateCcw,
  ChevronRight,
  GitBranch,
  Wrench
} from 'lucide-react';
import { FormattedChatMessage } from './FormattedChatMessage';

interface AutomaticAnalysisPanelProps {
  currentAnalysis: AutomaticAnalysisItem | null;
  recentAnalyses: AutomaticAnalysisItem[];
  failureHistory?: FailureEventHistoryItem[];
  isAnalyzing: boolean;
  lastAnalysisTime: string | null;
  aiError?: string | null;
  onManualReanalyze?: (equipmentId: string) => void;
  onAskAiFollowUp: (equipmentId: string, initialQuestion?: string) => void;
}

export const AutomaticAnalysisPanel: React.FC<AutomaticAnalysisPanelProps> = ({
  currentAnalysis,
  recentAnalyses = [],
  failureHistory = [],
  isAnalyzing,
  lastAnalysisTime,
  aiError,
  onManualReanalyze,
  onAskAiFollowUp
}) => {
  const [selectedHistoryId, setSelectedHistoryId] = useState<string | null>(null);

  // Active item to display (either history item clicked or current live analysis)
  const displayItem =
    (selectedHistoryId ? recentAnalyses.find((a) => a.id === selectedHistoryId) : null) ||
    currentAnalysis;

  if (!displayItem && !isAnalyzing) {
    return null;
  }

  const isFailure = displayItem?.isFailureConfirmed || displayItem?.stage === 'FAULT_CONFIRMED';
  const isUnknown = displayItem?.isUnknownFault;
  const isNominal = displayItem?.stage === 'NORMAL' && !isFailure && !isUnknown;
  const score = displayItem?.healthScore ?? 100;
  const equipId = displayItem?.equipmentId || 'pump';

  const followUpSuggestions = isFailure
    ? [
        'Why did this unit fail?',
        'What should I check first in the field?',
        'Could this be a false alarm / sensor issue?',
        'What are the immediate downstream shutdown risks?'
      ]
    : [
        'Why is this degradation occurring?',
        'What should I verify before failure trips?',
        'Could this be a sensor drift?',
        'What happens if this condition continues?'
      ];

  const getEquipmentIcon = (id?: string) => {
    switch (id?.toLowerCase()) {
      case 'pump':
      case 'p-101':
        return <Activity size={15} color="#EA580C" />;
      case 'heat_exchanger':
      case 'e-101':
        return <Flame size={15} color="#0891B2" />;
      case 'reactor':
      case 'r-101':
        return <Atom size={15} color="#7C3AED" />;
      case 'distillation':
      case 'd-101':
        return <Layers size={15} color="#2563EB" />;
      default:
        return <Sparkles size={15} color="var(--primary-blue)" />;
    }
  };

  return (
    <div
      className={`auto-analysis-panel ${isFailure ? 'failure-alert-mode' : isUnknown ? 'unknown-alert-mode' : ''}`}
      aria-label="Automatic AI Failure & Degradation Analysis Cockpit"
    >
      {/* 1. TOP HEADER & FAILURE ANNOUNCEMENT BAR */}
      <div className={`auto-header ${isFailure ? 'header-failure' : isUnknown ? 'header-unknown' : ''}`}>
        <div className="auto-header-left">
          <div className={`auto-sparkle-icon ${isFailure ? 'failure-icon' : ''}`}>
            {isFailure ? <AlertOctagon size={16} color="#FFFFFF" /> : <Sparkles size={15} color="#FFFFFF" />}
          </div>
          <div>
            <div className="auto-title-row">
              {isFailure ? (
                <span className="auto-title failure-text">🔴 FAILURE DETECTED — {displayItem?.equipmentName}</span>
              ) : isUnknown ? (
                <span className="auto-title unknown-text">⚠ UNKNOWN PROCESS ANOMALY — {displayItem?.equipmentName}</span>
              ) : (
                <span className="auto-title">AUTOMATIC AI PROBLEM ANALYSIS</span>
              )}
              <span className="auto-active-badge">
                <span className="auto-pulse-dot" />
                AUTOMATIC ANALYSIS ACTIVE
              </span>
            </div>
            <div className="auto-subtitle">
              {isFailure
                ? 'Deterministic fault confirmed. Real-time root-cause analysis automatically generated by Industrial AI.'
                : 'Continuous multivariable monitoring. Root-cause analysis automatically triggered upon degradation.'}
            </div>
          </div>
        </div>

        <div className="auto-header-right">
          {isAnalyzing ? (
            <div className="auto-status-analyzing">
              <span className="spin-anim">⟳</span>
              <span>{isFailure ? 'ANALYZING FAILURE...' : 'ANALYZING PROCESS...'}</span>
            </div>
          ) : aiError ? (
            <div className="auto-status-unavailable">
              <AlertTriangle size={12} color="#DC2626" />
              <span>AI ANALYSIS UNAVAILABLE</span>
            </div>
          ) : (
            <div className="auto-status-updated">
              <span className="auto-update-dot" />
              <span>ANALYSIS UPDATED</span>
              <span className="auto-time-tag">
                <Clock size={10} /> {lastAnalysisTime || displayItem?.timestamp || 'Live'}
              </span>
            </div>
          )}
        </div>
      </div>

      {/* 2. MAIN ANALYSIS CARD */}
      <div className={`auto-body-card ${isNominal ? 'nominal-theme' : isFailure ? 'failure-theme' : 'degradation-theme'}`}>
        {/* Top Unit Banner */}
        <div className="auto-unit-banner">
          <div className="auto-unit-tag-group">
            <div className="auto-unit-icon-box">{getEquipmentIcon(displayItem?.equipmentId)}</div>
            <div>
              <div className="flex items-center gap-2">
                <span className="auto-unit-name">{displayItem?.equipmentName || 'All Process Units'}</span>
                {isFailure && <span className="auto-failure-tag">CRITICAL FAILURE</span>}
                {isUnknown && <span className="auto-unknown-tag">UNCLASSIFIED ANOMALY</span>}
              </div>
              <span className={`auto-stage-pill ${isFailure ? 'pill-critical' : isNominal ? 'pill-healthy' : 'pill-warning'}`}>
                {displayItem?.stageLabel || displayItem?.stage || 'NOMINAL'}
              </span>
            </div>
          </div>

          <div className="auto-health-risk-group">
            <div className="auto-metric-pill">
              <span className="auto-metric-lbl">HEALTH</span>
              <span
                className="auto-metric-val"
                style={{ color: score >= 85 ? '#16A34A' : score >= 50 ? '#EA580C' : '#DC2626' }}
              >
                {score}%
              </span>
            </div>
            <div className="auto-metric-pill">
              <span className="auto-metric-lbl">RISK SCORE</span>
              <span
                className="auto-metric-val"
                style={{
                  color:
                    (displayItem?.riskScore ?? 12) > 60
                      ? '#DC2626'
                      : (displayItem?.riskScore ?? 12) > 30
                      ? '#EA580C'
                      : '#16A34A'
                }}
              >
                {displayItem?.riskScore ?? 12}/100
              </span>
            </div>
            <div className="auto-metric-pill">
              <span className="auto-metric-lbl">CONFIDENCE</span>
              <span className="auto-metric-val">{displayItem?.confidence ?? 92}%</span>
            </div>
          </div>
        </div>

        {/* Structured Sections */}
        <div className="auto-sections-grid">
          {/* Section A: What Happened */}
          <div className="auto-sec-item">
            <div className="auto-sec-label">
              <Activity size={12} color="var(--primary-blue)" />
              <span>{isFailure ? 'WHAT FAILED / WHAT HAPPENED' : 'WHAT IS HAPPENING'}</span>
            </div>
            <p className="auto-sec-text">{displayItem?.whatIsHappening}</p>
          </div>

          {/* Section B: Likely Root Cause */}
          <div className={`auto-sec-item ${isFailure ? 'highlight-failure-cause' : 'highlight-cause'}`}>
            <div className="auto-sec-label">
              <Wrench size={12} color={isFailure ? '#DC2626' : '#EA580C'} />
              <span>LIKELY ROOT CAUSE</span>
            </div>
            <p className="auto-sec-text">{displayItem?.whyItIsHappening}</p>
          </div>

          {/* Section C: Correlated Key Evidence */}
          <div className="auto-sec-item">
            <div className="auto-sec-label">
              <CheckCircle2 size={12} color="#16A34A" />
              <span>KEY EVIDENCE & SENSOR MEASUREMENTS</span>
            </div>
            <div className="auto-evidence-chips">
              {(displayItem?.evidence || []).map((ev, i) => (
                <div key={i} className="auto-evidence-chip">
                  <span className="auto-ev-check">✓</span>
                  <span>{ev}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Section D: Baseline Comparison */}
          {displayItem?.baselineComparison && (
            <div className="auto-sec-item">
              <div className="auto-sec-label">
                <Search size={12} color="var(--primary-blue)" />
                <span>BASELINE → CURRENT DEVIATION</span>
              </div>
              <p className="auto-sec-text font-mono-calc">{displayItem.baselineComparison}</p>
            </div>
          )}

          {/* Section E: Downstream Process Impact */}
          <div className="auto-sec-item">
            <div className="auto-sec-label">
              <GitBranch size={12} color="#0284C7" />
              <span>DOWNSTREAM PROCESS IMPACT</span>
            </div>
            <p className="auto-sec-text">{displayItem?.potentialImpact}</p>
          </div>

          {/* Section F: What to Verify */}
          <div className="auto-sec-item">
            <div className="auto-sec-label">
              <CheckCircle2 size={12} color="#0D9488" />
              <span>WHAT THE OPERATOR SHOULD VERIFY</span>
            </div>
            <p className="auto-sec-text">{displayItem?.whatToVerify}</p>
          </div>
        </div>

        {/* Bottom Action Footer & Follow-Up Bar */}
        <div className="auto-footer">
          <div className="auto-footer-left">
            <div className="flex items-center gap-2">
              <span className="auto-footer-note">
                {isFailure
                  ? '🔴 Critical fault automatically analyzed. Review verification steps before taking corrective action.'
                  : 'Automatic AI monitoring active. Analysis refreshed on process state transitions.'}
              </span>
            </div>
          </div>

          <div className="auto-footer-right">
            {onManualReanalyze && (
              <button
                className="auto-reanalyze-btn"
                onClick={() => onManualReanalyze(equipId)}
                title="Manually re-analyze using the latest process state"
              >
                <RotateCcw size={12} />
                <span>ANALYZE WITH AI</span>
              </button>
            )}

            <button
              className="auto-ask-ai-btn"
              onClick={() => {
                const prompt = `Following up on the failure diagnosis for ${displayItem?.equipmentName}: What specific physical checklist should I inspect first?`;
                onAskAiFollowUp(equipId, prompt);
              }}
              title="Open ChemDiag AI Copilot for interactive follow-up questions"
            >
              <MessageSquare size={13} />
              <span>Ask AI Follow-up</span>
            </button>
          </div>
        </div>

        {/* Quick Follow-up Chips */}
        <div className="auto-chips-container">
          <span className="auto-chips-lbl">QUICK FOLLOW-UP:</span>
          <div className="auto-chips-row">
            {followUpSuggestions.map((q, idx) => (
              <button
                key={idx}
                className="auto-chip-btn"
                onClick={() => onAskAiFollowUp(equipId, q)}
                title={`Ask AI: "${q}"`}
              >
                <span>{q}</span>
                <ChevronRight size={10} />
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* 3. RECENT AUTOMATIC ANALYSES & FAILURE EVENT TIMELINE */}
      {recentAnalyses.length > 0 && (
        <div className="auto-history-strip">
          <div className="auto-history-label">
            <History size={11} color="var(--primary-blue)" />
            <span>FAILURE & DEGRADATION HISTORY:</span>
          </div>

          <div className="auto-history-items">
            {recentAnalyses.map((item) => {
              const isSelected = selectedHistoryId === item.id;
              const isItemFailure = item.isFailureConfirmed || item.stage === 'FAULT_CONFIRMED';
              return (
                <button
                  key={item.id}
                  className={`auto-hist-btn ${isSelected ? 'selected' : ''} ${isItemFailure ? 'failure-hist-btn' : ''}`}
                  onClick={() => setSelectedHistoryId(isSelected ? null : item.id)}
                  title={`View analysis from ${item.timestamp} for ${item.equipmentName}`}
                >
                  <span className="auto-hist-time">{item.timestamp}</span>
                  <strong>{item.equipmentName.split(' ')[0]}</strong>
                  <span className={`auto-hist-stage ${isItemFailure ? 'failure-hist-text' : ''}`}>
                    {item.stageLabel}
                  </span>
                </button>
              );
            })}
            {selectedHistoryId && (
              <button
                className="auto-hist-live-btn"
                onClick={() => setSelectedHistoryId(null)}
              >
                ● Back to Live Analysis
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
export default AutomaticAnalysisPanel;
